config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  resources :adoption_applications, only: [:new, :create]
  resources :contact_messages, only: [:new, :create]
  resources :newsletters, only: [:index]
  resources :rat_adoptions, only: [:index]
  resources :resources, only: [:index]
  resources :volunteer_applications, only: [:new, :create]
  resource :donate, only: [:show]
  resource :volunteer, only: [:show]
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def show
  end
end

app/views/volunteers/index.html.erb
<div class="volunteer-text-image">
  <h2 class="question">
    Interested in becoming more involved with Any Rat Rescue?
  </h2>
  <div class ="volunteer-image">
    <%= image_tag("rat-3.jpg") %>
  </div>
  <div class="volunteer-text">
    <p>
      We are looking for people with enthusiasm, passion, and a love of rats to join our efforts.
      We have MANY volunteer opportunities. Below are some examples on how you can help. Please feel free to contact us for more information.
    </p>
    <h2>Fostering</h2>
    <p>
      We are in great need of foster homes. Since Any Rat Rescue does not have a brick-and-mortar shelter, the number of foster homes we have directly impacts the number of rats we can help. We turn rats away every day because we have nowhere to house them.
    </p>
    <p>
      If you have room in your home and your heart, please contact us for more information or fill out our foster application to get started.
    </p>
    <p>
      Any Rat Rescue will pay for any medical expenses your foster rat may need. All you need to provide is food, cleaning, socialization and most importantly LOVE!
    </p>
  </div>
  <div class ="volunteer-image">
      <%= image_tag("rat-2.jpg") %>
  </div>
  <div class="volunteer-text">
    <p>
      To help please fill out our <%=link_to "Foster Application", '#' %> and we will be in touch shortly.
    </p>
    <h2>
      Quarantine Homes:
    </h2>
    <p>
      Any Rat Rescue prides itself on good quality health care for their rats and this starts with the quarantine home. In order to make an accurate assessment of a rat's health, they are quarantined for three weeks where they undergo a course of medication for common infections. After these three weeks they can be moved to other homes with a much lower risk of infection transmission to other rats. 
    </p>
    <p>
      If you have a home with no other rodents we would greatly appreciate your support as a quarantine home.
    </p>
    <p>
      As with the foster homes, Any Rat Rescue will provide all medications and pay any vet expenses the rats may need.
    </p>
  </div>
  <div class ="volunteer-image">
    <%= image_tag("rat-4.jpg") %>
  </div>
  <div class="volunteer-text">
    <h2>
      Event support and Fundraising
    </h2>

    <p>
      Any Rat Rescue relies on volunteers to help at events. We often participate in adoption events with other rescues. 
    </p>
    <p>
      Events require several volunteers to run smoothly. We often have some of our rats at these events for potential adopters to meet. 
    </p>
    <p>
      Events allow the rescue to share information about rats and how to care for them. Spreading informaiton is just as important as finding homes for our rats. Well meaning rat owners often do not know how young male rats need to be separated from female rats. We often receive unwanted litters because owners thought they were too young to reproduce.
    </p>
    <h2>
      Sewing
    </h2>
    <p>
      Our rats love snuggling down for a sleep in cosy, warm hammocks and beds. Not only that but they make our cages look colorful and fun. If you are able to sew and would like to help our rats would greatly appreciate it. We can never have enough!
    </p>
  </div>
</div>

app/views/volunteers/show.html.erb
<div class="volunteer-text-image">
  <h2 class="question">
    Interested in becoming more involved with Any Rat Rescue?
  </h2>  
  <div class ="volunteer-image">
    <%= image_tag("rat-3.jpg") %>
  </div>
  <div>
    <button class="with-link">
      <%= link_to "Volunteer Today", new_volunteer_application_path %>
    </button>
  </div>
  <div class="volunteer-text">
    <p>
      We are looking for people with enthusiasm, passion, and a love of rats to
      join our efforts. We have MANY volunteer opportunities. Below are some
      examples on how you can help. Please feel free to contact us for more
      information.
    </p>
    <h2>Fostering</h2>
    <p>
      We are in great need of foster homes. Since Any Rat Rescue does not have
      a brick-and-mortar shelter, the number of foster homes we have directly
      impacts the number of rats we can help. We turn rats away every day
      because we have nowhere to house them.
    </p>
    <p>
      If you have room in your home and your heart, please contact us for more
      information or fill out our foster application to get started.
    </p>
    <p>
      Any Rat Rescue will pay for any medical expenses your foster rat may
      need. All you need to provide is food, cleaning, socialization and most
      importantly LOVE!
    </p>    
    <h2>
      Quarantine Homes:
    </h2>
  </div>
  <div class ="volunteer-image">
      <%= image_tag("rat-2.jpg") %>
  </div>
  <div class="volunteer-text">
    <p>
      Any Rat Rescue prides itself on good quality health care for their rats
      and this starts with the quarantine home. In order to make an accurate 
      assessment of a rat's health, they are quarantined for three weeks where
      they undergo a course of medication for common infections. After these
      three weeks they can be moved to other homes with a much lower risk of
      infection transmission to other rats. 
    </p>
    <p>
      If you have a home with no other rodents we would greatly appreciate your
      support as a quarantine home.
    </p>
    <p>
      As with the foster homes, Any Rat Rescue will provide all medications and
      pay any vet expenses the rats may need.
    </p>
    <p>
      If you are interested in either fostering or being a quarantine home
      please fill out our <%= link_to "Volunteer Application",
      new_volunteer_application_path %> and we will be in touch shortly.
    </p>

    <h2>
      Event support and Fundraising
    </h2>

    <p>
      Any Rat Rescue relies on volunteers to help at events. We often
      participate in adoption events with other rescues. 
    </p>
  </div>
  <div class ="volunteer-image">
    <%= image_tag("rat-4.jpg") %>
  </div>
  <div class="volunteer-text">
    <p>
      Events require several volunteers to run smoothly. We often have some of
      our rats at these events for potential adopters to meet. 
    </p>
    <p>
      Events allow the rescue to share information about rats and how to care
      for them. Spreading informaiton is just as important as finding homes for
      our rats. Well meaning rat owners often do not know how young male rats
      need to be separated from female rats. We often receive unwanted litters
      because owners thought their rats were too young to reproduce.
    </p>
    <h2>
      Sewing
    </h2>
    <p>
      Our rats love snuggling down for a sleep in cosy, warm hammocks and beds.
      Not only that but they make our cages look colorful and fun. If you are
      able to sew and would like to help our rats would greatly appreciate it.
      We can never have enough!
    </p>
  </div>
</div>