config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  resources :adoption_applications, only: [:new, :create]
  resources :contact_messages, only: [:new, :create]
  resources :newsletters, only: [:index]
  resources :rat_adoptions, only: [:index]
  resources :resources, only: [:index]
  resources :volunteer_applications, only: [:new, :create]
  resource :donate, only: [:show]
  resource :volunteer, only: [:show]
end

app/controllers/rat_adoptions_controller.rb
class RatAdoptionsController < ApplicationController
  ANY_RAT_RESCUE_PETFINDER_ID = "AZ173"

  def index
    @available_rats = available_rats
  end

  private

  def petfinder
    @_petfinder ||= Petfinder::Client.new
  end

  def any_rat_rescue
    @_any_rat_rescue ||= petfinder.shelter(ANY_RAT_RESCUE_PETFINDER_ID)
  end

  def available_rats
    @_available_rats ||= petfinder.shelter_pets(any_rat_rescue.id)
  end
end

app/views/rat_adoptions/index.html.erb
<div class="stats">
  <ul>
    <li><%= @available_rats.count %><span>Rats available</span></li>
    <li>"Adopted"<span>Adopted</span></li>
    <li>"Adopted last month"<span>Adopted last month</span></li>
  </ul>
</div>

<div class="text">
  <h2>Rats looking for their forever home.</h2>
  Mouse over their picture for their name. Click the image for more information.
</div>

<div class="button">
  <button class="with-link">
    <%= link_to "Adopt Today", new_adoption_application_path %>
  </button>
</div>

<div>
  <ul class="list-of-rats">
    <% @available_rats.each do |rat| %>
      <li>
        <%= link_to("http://www.petfinder.com/petdetail/#{rat.id}") do %>
          <%= image_tag rat.photos.first.medium, class: "rat-photo" %>
          <span class="rat-name-container">
            <span class="rat-name"><%= rat.name %></span>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<div class="text">
  We ask that anyone interested in adopting some rats fill out our <%= link_to "Adoption Application", new_adoption_application_path %> form.
</div>